// Mirrors the source-only CLI examples in scanner/examples/rule-fixtures.
import type { FixtureInput } from "./rule-fixture-contract.ts";

export const ruleFixtureExamples: Record<"call" | "taint", FixtureInput> = {
  "call": {
    "ruleYaml": "id: AEG-CUSTOM-001\nname: Review request argument\ndescription: Demonstrate a call selector against owned, non-executed source fixtures.\nseverity: medium\nconfidence: 0.7\nlanguages: [python]\npatterns:\n  - callee: '(?-i:review_target)'\n    callee_match_mode: full\n    args_match: request\n    args_match_index: 0\nmessage: Review request data passed to review_target; this is a static candidate.\n",
    "suiteJson": "{\n  \"schema_version\": 1,\n  \"suite_id\": \"custom-call\",\n  \"suite_version\": \"1.0.0\",\n  \"rule_id\": \"AEG-CUSTOM-001\",\n  \"cases\": [\n    {\n      \"id\": \"request-argument\",\n      \"files\": [{\"path\": \"handlers/main.py\", \"content\": \"def handle(request):\\n    return review_target(request)\\n\"}],\n      \"expected\": [{\"rule_id\": \"AEG-CUSTOM-001\", \"file_path\": \"handlers/main.py\", \"line_start\": 2}]\n    },\n    {\n      \"id\": \"constant-argument\",\n      \"files\": [{\"path\": \"handlers/main.py\", \"content\": \"def handle(request):\\n    return review_target('fixed')\\n\"}],\n      \"expected\": []\n    },\n    {\n      \"id\": \"different-callee\",\n      \"files\": [{\"path\": \"handlers/main.py\", \"content\": \"def handle(request):\\n    return different_target(request)\\n\"}],\n      \"expected\": []\n    },\n    {\n      \"id\": \"different-argument\",\n      \"files\": [{\"path\": \"handlers/main.py\", \"content\": \"def handle(request):\\n    return review_target('fixed', request)\\n\"}],\n      \"expected\": []\n    }\n  ]\n}\n"
  },
  "taint": {
    "ruleYaml": "id: AEG-TAINT-DEMO\nname: Review request data reaching a SQL argument\ndescription: Filter the scanner's modeled HTTP-parameter to SQL-query flows.\nseverity: high\nlanguages: [python]\ntaint:\n  source_types: [http_param]\n  sink_types: [sql_query]\nmessage: Review this statically modeled source-to-sink flow.\n",
    "suiteJson": "{\n  \"schema_version\": 1,\n  \"suite_id\": \"taint-demo\",\n  \"suite_version\": \"1.0.0\",\n  \"rule_id\": \"AEG-TAINT-DEMO\",\n  \"cases\": [\n    {\n      \"id\": \"request-query\",\n      \"files\": [{\"path\": \"main.py\", \"content\": \"def handler(request, cursor):\\n    query = request.args.get('query')\\n    return cursor.execute(query)\\n\"}],\n      \"expected\": [{\"rule_id\": \"AEG-TAINT-DEMO\", \"file_path\": \"main.py\", \"line_start\": 3}]\n    },\n    {\n      \"id\": \"constant-query\",\n      \"files\": [{\"path\": \"main.py\", \"content\": \"def handler(request, cursor):\\n    return cursor.execute('SELECT 1')\\n\"}],\n      \"expected\": []\n    },\n    {\n      \"id\": \"parameterized-query\",\n      \"files\": [{\"path\": \"main.py\", \"content\": \"def handler(request, cursor):\\n    value = request.args.get('value')\\n    return cursor.execute('SELECT ?', (value,))\\n\"}],\n      \"expected\": []\n    },\n    {\n      \"id\": \"cross-file-query\",\n      \"files\": [\n        {\"path\": \"handler.py\", \"content\": \"from helper import run_query\\ndef handler(request, cursor):\\n    query = request.args.get('query')\\n    return run_query(cursor, query)\\n\"},\n        {\"path\": \"helper.py\", \"content\": \"def run_query(cursor, value):\\n    return cursor.execute(value)\\n\"}\n      ],\n      \"expected\": [{\"rule_id\": \"AEG-TAINT-DEMO\", \"file_path\": \"helper.py\", \"line_start\": 2}]\n    }\n  ]\n}\n"
  }
};
